### ISSUE TITLE
Desarrollo

### ISSUE THREAD

**Issue by AguiarAlf** [AguiarAlf/PROYECTO-FINAL-2024-AAA#11]
Desarrollo (Descriptivo). Proceso de crear y validar todos los materiales de la enseñanza a ser implantada, donde incluye el desarrollo de la evaluación.
Apoyo de llenado. ¿De qué forma se desarrollará el curso? y ¿Cuál será la plataforma a utilizar y por qué?

**Comment by IluzAlan** [comment]
![Image](https://github.com/AguiarAlf/PROYECTO-FINAL-2024-AAA/assets/172995624/4ac94792-f112-461e-9be4-3495aa0be207)

**Comment by IluzAlan** [comment]
![Image](https://github.com/AguiarAlf/PROYECTO-FINAL-2024-AAA/assets/172995624/ea22a1d4-7c9b-4d80-944c-a14b965165d9)
