### ISSUE TITLE
Reunión de planificación

### ISSUE THREAD

**Issue by AguiarAlf** [AguiarAlf/PROYECTO-FINAL-2024-AAA#3]
Se determinan los rolos de cada integrante del equipo
Se define el tema y nivel educativo donde se aplicará
Nos dividimos las actividades a realizar

**Comment by AguiarAlf** [comment]
En esta reunión se hará la asignación de roles de cada miembro del equipo, así como la distribución de actividades y la determinación del tema del proyecto a realizar.

**Comment by 4riadn4-mc** [comment]
Se determino el área disciplinar para el desarrollo del proyecto.

**Comment by Alexma13** [comment]
![Image](https://github.com/AguiarAlf/PROYECTO-FINAL-2024-AAA/assets/172995787/9a30e613-5690-4709-9d0a-842aac920bcb)

Roles de equipo

**Comment by AguiarAlf** [comment]
![Image](https://github.com/AguiarAlf/PROYECTO-FINAL-2024-AAA/assets/172995692/3dea73ae-a629-4d78-82bd-d93142021fcf)

**Comment by Dr-RS** [comment]
Asignar Sesiones SIncrónicas, Flow Manager.

**Comment by 4riadn4-mc** [comment]
![Image](https://github.com/AguiarAlf/PROYECTO-FINAL-2024-AAA/assets/172996034/a3c24ecb-4641-4227-97b3-1154b22322ed)

Sesión de planificación
