### ISSUE TITLE
Tercera sesión sincrónica

### ISSUE THREAD

**Issue by AguiarAlf** [AguiarAlf/PROYECTO-FINAL-2024-AAA#5]

**Comment by 4riadn4-mc** [comment]
En esta sesión se concluyo la integración del anteproyecto y se complementó la presentación.


![Image](https://github.com/AguiarAlf/PROYECTO-FINAL-2024-AAA/assets/172996034/4cbcfbc6-2807-4b84-b79e-b36abd92d27a)
