### ISSUE TITLE
Análisis

### ISSUE THREAD

**Issue by AguiarAlf** [AguiarAlf/PROYECTO-FINAL-2024-AAA#9]
Análisis (Descriptivo: Cuál será el método que se utilizará para realizar el análisis). Se recoge y analiza información del proyecto en general. Se detectan necesidades de instrucción. Se toma en cuenta la audiencia, los recursos disponibles y en general, todo lo involucrado en la tarea.
Apoyo de llenado. En esta sección trata de responder a las preguntas: ¿Cuál es la situación actual?,¿Cuál es el objetivo de la propuesta?, ¿Por qué lo hacemos?, ¿Cómo ayudará a los estudiantes?

**Comment by 4riadn4-mc** [comment]
Se definirán los Objetivos del Curso, Necesidades y el Perfil de los Estudiantes...
